# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Pal\Desktop\pal_del3\pal_del3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1380, 957)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:rgb(61, 28, 85)")
        self.centralwidget.setObjectName("centralwidget")
        self.Warning_On = QtWidgets.QPushButton(self.centralwidget)
        self.Warning_On.setGeometry(QtCore.QRect(80, 700, 211, 131))
        self.Warning_On.setStyleSheet("QPushButton{\n"
"   border: none;\n"
"   background-color:rgb(0, 0, 0);\n"
"   color: rgb(255, 255, 255);\n"
"    font: 8pt \"MS Reference Specialty\";\n"
"    font: 14pt \"Gill Sans Ultra Bold\";\n"
"   border-left: 1px solid rgb(0, 0, 0);\n"
"   border-right:1px solid rgb(0, 0, 0);\n"
"   border-bottom: 5px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"   border: none;\n"
"   background-color:rgb(160, 160, 245);\n"
"   border-left: 1px solid rgb(160, 160, 245);\n"
"   border-right:1px solid rgb(160, 160, 245);\n"
"   border-bottom: 5px solid rgb(160, 160, 245);\n"
"  \n"
"}")
        self.Warning_On.setObjectName("Warning_On")
        self.Warning_Off = QtWidgets.QPushButton(self.centralwidget)
        self.Warning_Off.setGeometry(QtCore.QRect(80, 560, 211, 121))
        self.Warning_Off.setStyleSheet("QPushButton{\n"
"   border: none;\n"
"   background-color:rgb(0, 0, 0);\n"
"   color: rgb(255, 255, 255);\n"
"    font: 8pt \"MS Reference Specialty\";\n"
"    font: 14pt \"Gill Sans Ultra Bold\";\n"
"   border-left: 1px solid rgb(0, 0, 0);\n"
"   border-right:1px solid rgb(0, 0, 0);\n"
"   border-bottom: 5px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"   border: none;\n"
"   background-color:rgb(160, 160, 245);\n"
"   border-left: 1px solid rgb(160, 160, 245);\n"
"   border-right:1px solid rgb(160, 160, 245);\n"
"   border-bottom: 5px solid rgb(160, 160, 245);\n"
"  \n"
"}")
        self.Warning_Off.setObjectName("Warning_Off")
        self.Send_Command = QtWidgets.QTextEdit(self.centralwidget)
        self.Send_Command.setGeometry(QtCore.QRect(920, 560, 381, 281))
        self.Send_Command.setStyleSheet("QTextEdit{\n"
"  border: 2px solid rgb(37, 39, 48);\n"
"  border-radius: 20px;\n"
"padding-top: 20px;\n"
"  color: #FFF;\n"
"  padding-left: 20px;\n"
" font: 12pt \"Gill Sans Ultra Bold\";\n"
"  padding-right: 20px;\n"
"  background-color: rgb(34, 36, 44);\n"
"}\n"
"\n"
"QTextEdit:hover {\n"
"  border: 2px solid rgb(143, 142, 141);\n"
"}\n"
"\n"
"QTextEdit:focus{\n"
"  border: 2px rgb(143, 142, 141);\n"
"}")
        self.Send_Command.setObjectName("Send_Command")
        self.Submit = QtWidgets.QPushButton(self.centralwidget)
        self.Submit.setGeometry(QtCore.QRect(1190, 780, 81, 41))
        self.Submit.setStyleSheet("QPushButton{\n"
"   border: none;\n"
"   background-color:rgb(0, 0, 0);\n"
"     border-radius: 20px;\n"
"   color: rgb(255, 255, 255);\n"
"    font: 87 8pt \"Arial Black\";\n"
"   border-left: 1px solid rgb(0, 0, 0);\n"
"   border-right:1px solid rgb(0, 0, 0);\n"
"   border-bottom: 5px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"   border: none;\n"
"   background-color:rgb(160, 160, 245);\n"
"   border-left: 1px solid rgb(160, 160, 245);\n"
"   border-right:1px solid rgb(160, 160, 245);\n"
"   border-bottom: 5px solid rgb(160, 160, 245);\n"
"  \n"
"}")
        self.Submit.setObjectName("Submit")
        self.Spot_1 = QtWidgets.QFrame(self.centralwidget)
        self.Spot_1.setGeometry(QtCore.QRect(110, 170, 171, 221))
        self.Spot_1.setStyleSheet("QFrame{\n"
"image: url(:/icon/sedan-car-front.png);}")
        self.Spot_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Spot_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Spot_1.setObjectName("Spot_1")
        self.Spot_2 = QtWidgets.QFrame(self.centralwidget)
        self.Spot_2.setGeometry(QtCore.QRect(340, 170, 171, 221))
        self.Spot_2.setStyleSheet("\n"
"image: url(:/icon/car.png);")
        self.Spot_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Spot_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Spot_2.setObjectName("Spot_2")
        self.Spot_3 = QtWidgets.QFrame(self.centralwidget)
        self.Spot_3.setGeometry(QtCore.QRect(570, 170, 171, 221))
        self.Spot_3.setStyleSheet("image: url(:/icon/car (1).png);")
        self.Spot_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Spot_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Spot_3.setObjectName("Spot_3")
        self.Spot_4 = QtWidgets.QFrame(self.centralwidget)
        self.Spot_4.setGeometry(QtCore.QRect(800, 170, 171, 221))
        self.Spot_4.setStyleSheet("image: url(:/icon/car (2).png);")
        self.Spot_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Spot_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Spot_4.setObjectName("Spot_4")
        self.Spot_5 = QtWidgets.QFrame(self.centralwidget)
        self.Spot_5.setGeometry(QtCore.QRect(1020, 170, 171, 221))
        self.Spot_5.setStyleSheet("image: url(:/icon/drive.png);")
        self.Spot_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Spot_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Spot_5.setObjectName("Spot_5")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(110, 420, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.checkBox.setStyleSheet("QCheckBox::indicator{\n"
"\n"
"width: 35px;\n"
"height: 35px;\n"
"}\n"
"\n"
"QCheckBox::hover{\n"
"color: rgb(255, 255, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"image: url(:/newPrefix/unchecked.png);\n"
"}\n"
"\n"
"QCheckBox::indicatior:unchecked, QCheckBox::indicator:unchecked:pressed{\n"
"image: url(:/newPrefix/check.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
"image: url(:/newPrefix/check.png);\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(1020, 420, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.checkBox_6.setStyleSheet("QCheckBox::indicator{\n"
"\n"
"width: 35px;\n"
"height: 35px;\n"
"}\n"
"\n"
"QCheckBox::hover{\n"
"color: rgb(255, 255, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"image: url(:/newPrefix/unchecked.png);\n"
"}\n"
"\n"
"QCheckBox::indicatior:unchecked, QCheckBox::indicator:unchecked:pressed{\n"
"image: url(:/newPrefix/check.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
"image: url(:/newPrefix/check.png);\n"
"}")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setGeometry(QtCore.QRect(800, 420, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.checkBox_7.setStyleSheet("QCheckBox::indicator{\n"
"\n"
"width: 35px;\n"
"height: 35px;\n"
"}\n"
"\n"
"QCheckBox::hover{\n"
"color: rgb(255, 255, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"image: url(:/newPrefix/unchecked.png);\n"
"}\n"
"\n"
"QCheckBox::indicatior:unchecked, QCheckBox::indicator:unchecked:pressed{\n"
"image: url(:/newPrefix/check.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
"image: url(:/newPrefix/check.png);\n"
"}")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8.setGeometry(QtCore.QRect(570, 420, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.checkBox_8.setStyleSheet("QCheckBox::indicator{\n"
"\n"
"width: 35px;\n"
"height: 35px;\n"
"}\n"
"\n"
"QCheckBox::hover{\n"
"color: rgb(255, 255, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"image: url(:/newPrefix/unchecked.png);\n"
"}\n"
"\n"
"QCheckBox::indicatior:unchecked, QCheckBox::indicator:unchecked:pressed{\n"
"image: url(:/newPrefix/check.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
"image: url(:/newPrefix/check.png);\n"
"}")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_9.setGeometry(QtCore.QRect(340, 420, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.checkBox_9.setStyleSheet("QCheckBox::indicator{\n"
"\n"
"width: 35px;\n"
"height: 35px;\n"
"}\n"
"\n"
"QCheckBox::hover{\n"
"color: rgb(255, 255, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked{\n"
"image: url(:/newPrefix/unchecked.png);\n"
"}\n"
"\n"
"QCheckBox::indicatior:unchecked, QCheckBox::indicator:unchecked:pressed{\n"
"image: url(:/newPrefix/check.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked{\n"
"image: url(:/newPrefix/check.png);\n"
"}")
        self.checkBox_9.setObjectName("checkBox_9")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 40, 1101, 91))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"\n"
"  border: 2px solid rgb(37, 39, 48);\n"
"  border-radius: 20px;\n"
"  color:  rgb(255, 255, 255);\n"
"    font: 75 48pt \"Calibri\";\n"
"  background-color: rgb(34, 36, 44);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"  border: 2px solid rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"  border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.Terminal = QtWidgets.QLabel(self.centralwidget)
        self.Terminal.setGeometry(QtCore.QRect(390, 560, 471, 281))
        self.Terminal.setStyleSheet("QLabel{\n"
"    font: 75 12pt \"Terminal\";\n"
"  border: 2px solid rgb(37, 39, 48);\n"
"  border-radius: 20px;\n"
"  color: rgb(0, 177, 0);\n"
"  padding-left: 20px;\n"
"  padding-top: 20px;\n"
"  padding-right: 20px;\n"
"  background-color: rgb(34, 36, 44);\n"
"}\n"
"\n"
"QLabel:hover {\n"
"  border: 2px solid rgb(48, 50, 62);\n"
"padding-left: 20px;\n"
"  padding-top: 30px;\n"
"}\n"
"\n"
"QLabel:focus{\n"
"  border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.Terminal.setText("")
        self.Terminal.setObjectName("Terminal")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1380, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Warning_On.setText(_translate("MainWindow", "ON"))
        self.Warning_Off.setText(_translate("MainWindow", "OFF"))
        self.Send_Command.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gill Sans Ultra Bold\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Submit.setText(_translate("MainWindow", "Submit"))
        self.checkBox.setText(_translate("MainWindow", "Parking Spot 1"))
        self.checkBox_6.setText(_translate("MainWindow", "Parking Spot 5"))
        self.checkBox_7.setText(_translate("MainWindow", "Parking Spot 4"))
        self.checkBox_8.setText(_translate("MainWindow", "Parking Spot 3"))
        self.checkBox_9.setText(_translate("MainWindow", "Parking Spot 2"))
        self.lineEdit.setText(_translate("MainWindow", "                           AVAILABLE SPOTS"))
import test_rc
